name: global-proxy

x-defaults:
  network: &network
    networks:
      - dev-proxy-network # All dev containers must join this shared network

services:
  caddy:
    image: caddy:latest
    container_name: global-proxy-caddy
    restart: unless-stopped
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3 support
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
      - caddy_data:/data
      - caddy_config:/config
    <<: *network

networks:
  dev-proxy-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
